package mdadm

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/NimoTech/NimoOS-Common/utils/logger"
	"go.uber.org/zap"
)

const DefaultMdadmPath = "mdadm"

// MdadmPath is the path to the mdadm binary: the distribution's mdadm, resolved
// through PATH, unless MDADM_PATH overrides it.
var MdadmPath = resolveMdadmPath()

func resolveMdadmPath() string {
	if p := os.Getenv("MDADM_PATH"); p != "" {
		return p
	}
	return DefaultMdadmPath
}

// CheckSupport reports whether the mdadm binary can be found, so callers can
// log a useful message at startup instead of surfacing an exec failure on the
// first RAID operation.
func CheckSupport() error {
	if _, err := exec.LookPath(MdadmPath); err != nil {
		return fmt.Errorf("%s not found: please install mdadm", MdadmPath)
	}
	return nil
}

// Create creates a new RAID array.
// mdadm --create <device> --level=<level> --raid-devices=<n> [--chunk=<kb>] --run <members...>
func Create(device string, level int, members []string, chunkKB int) error {
	args := []string{
		"--create", device,
		fmt.Sprintf("--level=%d", level),
		fmt.Sprintf("--raid-devices=%d", len(members)),
	}
	// chunk size only applies to RAID 0, 5, 6; RAID 1 forbids it
	if chunkKB > 0 && level != 1 {
		args = append(args, fmt.Sprintf("--chunk=%d", chunkKB))
	}
	args = append(args, "--run")
	args = append(args, members...)

	logger.Info("mdadm create", zap.String("device", device), zap.Int("level", level), zap.Strings("members", members))
	out, err := exec.Command(MdadmPath, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("mdadm create %s: %w: %s", device, err, string(out))
	}
	return nil
}

// Stop stops a RAID array: mdadm --stop <device>
func Stop(device string) error {
	logger.Info("mdadm stop", zap.String("device", device))
	out, err := exec.Command(MdadmPath, "--stop", device).CombinedOutput()
	if err != nil {
		return fmt.Errorf("mdadm stop %s: %w: %s", device, err, string(out))
	}
	return nil
}

// Detail runs `mdadm --detail <device>` and parses output using ParseDetail from parse.go.
func Detail(device string) (*ArrayDetail, error) {
	out, err := exec.Command(MdadmPath, "--detail", device).CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("mdadm detail %s: %w: %s", device, err, string(out))
	}
	return ParseDetail(string(out))
}

// ReadMDStat reads /proc/mdstat and parses using ParseMDStat from parse.go.
func ReadMDStat() ([]MDStatEntry, error) {
	data, err := os.ReadFile("/proc/mdstat")
	if err != nil {
		return nil, fmt.Errorf("read /proc/mdstat: %w", err)
	}
	return ParseMDStat(string(data))
}

// AddDisk adds a disk to array: mdadm <arrayDevice> --add <diskDevice>
func AddDisk(arrayDevice, diskDevice string) error {
	logger.Info("mdadm add disk", zap.String("array", arrayDevice), zap.String("disk", diskDevice))
	out, err := exec.Command(MdadmPath, arrayDevice, "--add", diskDevice).CombinedOutput()
	if err != nil {
		return fmt.Errorf("mdadm add disk %s to %s: %w: %s", diskDevice, arrayDevice, err, string(out))
	}
	return nil
}

// RemoveDisk marks faulty + removes: mdadm <arrayDevice> --fail <diskDevice> --remove <diskDevice>
func RemoveDisk(arrayDevice, diskDevice string) error {
	logger.Info("mdadm remove disk", zap.String("array", arrayDevice), zap.String("disk", diskDevice))
	out, err := exec.Command(MdadmPath, arrayDevice, "--fail", diskDevice, "--remove", diskDevice).CombinedOutput()
	if err != nil {
		return fmt.Errorf("mdadm remove disk %s from %s: %w: %s", diskDevice, arrayDevice, err, string(out))
	}
	return nil
}

// AssembleScan reassembles all known arrays: mdadm --assemble --scan
// NOTE: may return non-zero if arrays already active — log but don't fail
func AssembleScan() error {
	logger.Info("mdadm assemble scan")
	out, err := exec.Command(MdadmPath, "--assemble", "--scan").CombinedOutput()
	if err != nil {
		logger.Info("mdadm assemble scan returned non-zero (arrays may already be active)", zap.String("output", string(out)))
	}
	return nil
}

// ConfigPath is the boot-time array config regenerated by SaveConfig.
var ConfigPath = "/etc/mdadm/mdadm.conf"

// SaveConfig regenerates ConfigPath from the currently active arrays:
// `mdadm --detail --scan` prints one ARRAY line per live array, so this both
// records arrays that were just created and drops ones that have been stopped.
// With no arrays left it prints nothing and exits 0, so an empty config is a
// legitimate result, not a failure.
//
// The scan output lands in a temp file that replaces ConfigPath only once mdadm
// has exited cleanly. This used to be `bash -c "mdadm --detail --scan > path"`,
// where the shell truncates the target while setting up the redirect — before
// mdadm runs — so a transient mdadm failure emptied the config and every
// surviving array lost its boot-time ARRAY line.
func SaveConfig() error {
	logger.Info("mdadm save config", zap.String("path", ConfigPath))

	scan, err := exec.Command(MdadmPath, "--detail", "--scan").Output()
	if err != nil {
		stderr := ""
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			stderr = strings.TrimSpace(string(exitErr.Stderr))
		}
		return fmt.Errorf("failed to scan arrays for mdadm config: %w\noutput: %s", err, stderr)
	}

	dir := filepath.Dir(ConfigPath)
	tmp, err := os.CreateTemp(dir, filepath.Base(ConfigPath)+".tmp-*")
	if err != nil {
		return fmt.Errorf("failed to create temporary mdadm config in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	// Both are no-ops once the rename below has succeeded.
	defer func() {
		tmp.Close()
		os.Remove(tmpPath)
	}()

	if _, err := tmp.Write(scan); err != nil {
		return fmt.Errorf("failed to write temporary mdadm config %s: %w", tmpPath, err)
	}
	// CreateTemp makes the file 0600; the config is world-readable state.
	if err := tmp.Chmod(0o644); err != nil {
		return fmt.Errorf("failed to chmod temporary mdadm config %s: %w", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("failed to close temporary mdadm config %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, ConfigPath); err != nil {
		return fmt.Errorf("failed to replace mdadm config %s: %w", ConfigPath, err)
	}
	return nil
}

// ZeroSuperblock clears superblock: mdadm --zero-superblock <device>
func ZeroSuperblock(device string) error {
	logger.Info("mdadm zero superblock", zap.String("device", device))
	out, err := exec.Command(MdadmPath, "--zero-superblock", device).CombinedOutput()
	if err != nil {
		return fmt.Errorf("mdadm zero-superblock %s: %w: %s", device, err, string(out))
	}
	return nil
}

// NextAvailableDevice returns next free /dev/mdN (checks /proc/mdstat, tries 0-127).
func NextAvailableDevice() (string, error) {
	entries, err := ReadMDStat()
	if err != nil {
		return "", fmt.Errorf("next available device: %w", err)
	}

	used := make(map[string]bool)
	for _, e := range entries {
		used[e.Device] = true
	}

	for i := 0; i < 128; i++ {
		name := fmt.Sprintf("md%d", i)
		if !used[name] {
			return "/dev/" + name, nil
		}
	}
	return "", fmt.Errorf("no available /dev/mdN device in range 0-127")
}

// LevelName converts 5 → "raid5".
func LevelName(level int) string {
	return fmt.Sprintf("raid%d", level)
}

// ParseLevelNumber converts "raid5" → 5.
func ParseLevelNumber(level string) (int, error) {
	lower := strings.ToLower(strings.TrimSpace(level))
	if !strings.HasPrefix(lower, "raid") {
		return 0, fmt.Errorf("invalid raid level name %q: must start with \"raid\"", level)
	}
	n, err := strconv.Atoi(lower[4:])
	if err != nil {
		return 0, fmt.Errorf("invalid raid level name %q: %w", level, err)
	}
	return n, nil
}

// EnsureModuleLoaded attempts to load the necessary kernel modules (md_mod, raid0, etc.)
func EnsureModuleLoaded(level int) error {
	modules := []string{"md_mod"}
	switch level {
	case 0:
		modules = append(modules, "raid0")
	case 1:
		modules = append(modules, "raid1")
	case 5:
		modules = append(modules, "raid5")
	case 6:
		modules = append(modules, "raid6")
	case 10:
		modules = append(modules, "raid10")
	}

	for _, mod := range modules {
		if out, err := exec.Command("modprobe", mod).CombinedOutput(); err != nil {
			logger.Error("failed to load kernel module", zap.String("module", mod), zap.Error(err), zap.String("output", string(out)))
			// We continue even if modprobe fails, as the module might be built-in or already loaded.
		}
	}
	return nil
}
