// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Mount defines model for Mount.
type Mount struct {
	// Extended Extended properties of the mount
	Extended   *map[string]string `json:"extended,omitempty"`
	Fstype     *string            `json:"fstype,omitempty"`
	Id         *int               `json:"id,omitempty"`
	MountPoint string             `json:"mount_point"`
	Options    *string            `json:"options,omitempty"`
	Source     *string            `json:"source,omitempty"`
}

// AddMountResponseOK defines model for AddMountResponseOK.
type AddMountResponseOK struct {
	Data *Mount `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetMountsResponseOK defines model for GetMountsResponseOK.
type GetMountsResponseOK struct {
	Data *[]Mount `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseForbidden defines model for ResponseForbidden.
type ResponseForbidden = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// UmountResponseOK defines model for UmountResponseOK.
type UmountResponseOK = BaseResponse

// UpdateMountResponseOK defines model for UpdateMountResponseOK.
type UpdateMountResponseOK struct {
	Data *Mount `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// UmountParams defines parameters for Umount.
type UmountParams struct {
	// MountPoint Filter the results by mount point
	MountPoint string `form:"mount_point" json:"mount_point"`
}

// GetMountsParams defines parameters for GetMounts.
type GetMountsParams struct {
	// Id Filter the results by id
	Id *string `form:"id,omitempty" json:"id,omitempty"`

	// MountPoint Filter the results by mount point
	MountPoint *string `form:"mount_point,omitempty" json:"mount_point,omitempty"`

	// Type Filter the results by type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Source Filter the results by source
	Source *string `form:"source,omitempty" json:"source,omitempty"`
}

// UpdateMountParams defines parameters for UpdateMount.
type UpdateMountParams struct {
	// MountPoint Filter the results by mount point
	MountPoint string `form:"mount_point" json:"mount_point"`
}

// MountJSONRequestBody defines body for Mount for application/json ContentType.
type MountJSONRequestBody = Mount

// UpdateMountJSONRequestBody defines body for UpdateMount for application/json ContentType.
type UpdateMountJSONRequestBody = Mount

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Umount volume
	// (DELETE /mount)
	Umount(ctx echo.Context, params UmountParams) error
	// Get mounted volumes
	// (GET /mount)
	GetMounts(ctx echo.Context, params GetMountsParams) error
	// Mount a volume
	// (POST /mount)
	Mount(ctx echo.Context) error
	// Update a mount volume
	// (PUT /mount)
	UpdateMount(ctx echo.Context, params UpdateMountParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Umount converts echo context to params.
func (w *ServerInterfaceWrapper) Umount(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UmountParams
	// ------------- Required query parameter "mount_point" -------------

	err = runtime.BindQueryParameter("form", true, true, "mount_point", ctx.QueryParams(), &params.MountPoint)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mount_point: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Umount(ctx, params)
	return err
}

// GetMounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetMounts(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMountsParams
	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", ctx.QueryParams(), &params.Id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Optional query parameter "mount_point" -------------

	err = runtime.BindQueryParameter("form", true, false, "mount_point", ctx.QueryParams(), &params.MountPoint)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mount_point: %s", err))
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", ctx.QueryParams(), &params.Source)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMounts(ctx, params)
	return err
}

// Mount converts echo context to params.
func (w *ServerInterfaceWrapper) Mount(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Mount(ctx)
	return err
}

// UpdateMount converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMount(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateMountParams
	// ------------- Required query parameter "mount_point" -------------

	err = runtime.BindQueryParameter("form", true, true, "mount_point", ctx.QueryParams(), &params.MountPoint)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mount_point: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateMount(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/mount", wrapper.Umount)
	router.GET(baseURL+"/mount", wrapper.GetMounts)
	router.POST(baseURL+"/mount", wrapper.Mount)
	router.PUT(baseURL+"/mount", wrapper.UpdateMount)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYTW8bvRH+KwTbQwystXpjH1IBPth14waJ7SB2eqhlCBQ5WjHZJTecoWzV0H8vSK6+",
	"N66qNG6AnGwtOZ985uEMn7i0VW0NGELee+IOsLYGIf44VerSekOfmo/X78NXaQ2BofCvqOtSS0HamvwL",
	"WhO+oRxDJeJqWV6PeO/uif/ZwYj3+J/ypbE87cP8TCDMDfBZ9sRrZ2twpJMPSlBU9pyK6CSfzTJO0xp4",
	"j9vhF5DEZ/cZdyDUtSmnvEfOwyxsUoDS6Tp4zXv8+j2fZfwCKGrBXyFWTVDhjkEvYhbOiemPJWHu2plQ",
	"n+CbB6QdcgCPoqpLCP9WgCiKYPtMKDZXMct+ME+7BLBhcC78V2tGpZZ7x7GQf5EgVq3NJd9aN9RKgdk3",
	"hKWCF4lhzdxc9MrSW+uN2jeGK0ssKXiRGNbMfa5emAJ3r9fPtRIEvwdFLw4+mlzzqLfp0AI4TxuKmgXm",
	"gLwzoNhwyhDcBBxDrYDpEaMxOGAamTBTni3hyPmmo4tQkJw2BY+Opzi3PIJHAqMgFoBQSgd/RPlxbc+G",
	"ts0k/K1RwZaamY3+sojQVWdDClwBboQddDIuI+/xvDKUi178M+TbZ5HxEaZPK3XIRx6hM9fHs20/tUqd",
	"Q2tytCEowIV90Y9BbXXK0NJCfn56e9qm2cbgcX23gpHwJWEmytI+DGw4sUwKgsK6aUc6EAQn1Qizyk4g",
	"wNBiLU+iU5U2IweAtZBw8sdlm0m03smNDKznbfvcAzK+ee3C+d6thXm/leNgAqR3mqY3Ac/p7IWUgDgg",
	"+zURvQ4nPgahwPGMG1EFFaeextbpf8ViXrohav0epgl+2ozsNuz7vts9krWW5B3EH9A3jDGWFlLIrAKl",
	"xUmfv6odjMDhobSldYex6qDHlHBfD/qcoZMIdNLnY6Iae3nuxEOn0DT2Q4/gGurpSFvlV7qytyDHeWkL",
	"m1dCm9zoylps/gyGwhhwg6B6YHQxpsGbbrd+7NSm6PN9HS2Dop/kKT3oqH4wLD0876yuCibKYD4ov75J",
	"Dr2sN8mTfOPk+yZ5xD5YKUp2Q9YFUgxEqEN6hREFICvjKjar2sjSK20KpjR+xYzVwlHksUCVKnFQWI7A",
	"x04wczvWyE4/vmOxUpEFLnBCxm0PmsaRvOZmyTJpjfKSGHo5btyoQk6CrrfWMY3oIZlTGqVHDOYzVpcg",
	"ENhEo6ao8+5C09/9kDmoLWqybnr/ap72lPL1PKd8HDDr2BerDbuz3rFzjdI6tZRU6UMU1WaiCfI3Vzd0",
	"cfkA/xwfdEJFaoqE0Zrf04/veMYn4DBV5eR1ojgwota8x4863c4Rz3gtaBxJIa/ml4mCEqjlPnt1e31+",
	"fcCjFhdp4Z3ivaZliaqcqIDAYbzjNzo1XRK4mC8HGBg1XIdRNB0izxIPffPgpksaWuW3VeZLtL/sLf4j",
	"v6e7f2XefN3tfq+PWOzLt/qxWcaPdxFsmW6i6NHuomvN7XH3eHfJRQccBf+yu+ByJgg3h68q4aaLI2YT",
	"W/oKQmpFEc449R+sAhpbhfx+lvECaBs4F0ChKBt5ZNI7B4bK5vxBMWtSdU6RoOqwf8w3CsOGwEYRO6mB",
	"ktYltyM7RLCwJfA6W+hcjNr7AVSr7+AyLrTBr9t2Zf+camhF//7mo1i73WapzSA80vH+NpsGqN3qYrE1",
	"UAWTHJX4439V6m2PMutlEHA8R2yD5WeLobZIO9PoZcOiLrHFmVXT/2q42mUemm0y6GyfRLU81P3/WPHH",
	"yS2dm9iF3Wrfcp5xLg5kJNgqTYapLuR6IkowFBoObxZtS6iCZttaO6OJiUJos2xYDDw8y28rU/kvdAV/",
	"ryZ/dWi3v3H8nnd+TMUGqJ+pjtVZM4Jvfcq8uw8ISM8fCZzelQEqk9d57P0HTe8fH2kaI5sI/mAfDkuY",
	"QNm0tw1A113ZvnrSYBIHYHEOI23iJMEShD7B6KT/DLb6nOVpltkwGB19PCRRXDjr6+Tv2oZnqGSx86Z5",
	"ZtrYy+9n97N/BwAA//8NJWzBLxkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
