name: goreleaser

on:
  push:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  call-workflow-passing-data:
    uses: NimoTech/github/.github/workflows/go_release.yml@main
    with:
      project-name: NimoOS-LocalStorage
      file-name: nimoos-local-storage
    secrets:
      OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
      OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}